services:
  # The MongoDB Database
  mongodb:
    image: mongo
    container_name: mongodb
    restart: on-failure
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - isolated_network

  # 1. Internal Server (Serves files to Lavalink using the hostname "playlists")
  playlists:
    image: nginx:alpine
    container_name: playlists
    restart: on-failure
    user: root
    command: /bin/sh -c "sed -i 's/user  nginx;/user  root;/g' /etc/nginx/nginx.conf && nginx -g 'daemon off;'"
    volumes:
      - ./playlist:/usr/share/nginx/html:ro
    networks:
      - isolated_network

  icecast:
    image: infiniteproject/icecast
    container_name: icecast
    command: ["icecast", "-c", "/opt/icecast.xml"]
    volumes:
      - ./icecast.xml:/opt/icecast.xml:ro
    environment:
      - ICECAST_SOURCE_PASSWORD=youshallnotpass
      - ICECAST_ADMIN_PASSWORD=youshallnotpass
    ports:
      - "8000:8000"
    networks:
      - isolated_network

  liquidsoap:
    image: savonet/liquidsoap:v2.4.5
    container_name: liquidsoap
    user: "1000:1000"
    command: liquidsoap /etc/liquidsoap/radio.liq
    volumes:
      - ./playlist:/playlist:ro
      - ./radio.liq:/etc/liquidsoap/radio.liq:ro
    depends_on:
      - icecast
    networks:
      - isolated_network

  # The VPN Container (Handles the secure connection from your friends)
  tailscale_vpn:
    image: tailscale/tailscale:latest
    container_name: tailscale_vpn
    hostname: music-filebrowser
    ports:
      - "2333:2333"
    environment:
      - TS_STATE_DIR=/var/lib/tailscale
    volumes:
      - tailscale_data:/var/lib/tailscale
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
      - sys_module
    restart: on-failure
    networks:
      - isolated_network

  # 2. Web File Manager (Allows password-protected uploads/deletions via browser)
  filebrowser:
    image: filebrowser/filebrowser:latest
    container_name: filebrowser
    restart: on-failure
    volumes:
      - ./playlist:/srv
      - filebrowser_data:/database
    network_mode: service:tailscale_vpn

  # The Lavalink Server
  lavalink:
    image: ghcr.io/lavalink-devs/lavalink
    container_name: lavalink
    restart: on-failure
    network_mode: service:tailscale_vpn
    environment:
      - LAVALINK_SERVER_PASSWORD=youshallnotpass
      - SERVER_PORT=2333
      - SERVER_ADDRESS=0.0.0.0
      - LAVALINK_SERVER_SOURCES_YOUTUBE=false
      - LAVALINK_SERVER_SOURCES_BANDCAMP=false
      - LAVALINK_SERVER_SOURCES_SOUNDCLOUD=false
      - LAVALINK_SERVER_SOURCES_TWITCH=false
      - LAVALINK_SERVER_SOURCES_VIMEO=false
      - LAVALINK_SERVER_SOURCES_NICO=false
      - LAVALINK_SERVER_SOURCES_HTTP=true
      - LAVALINK_SERVER_SOURCES_LOCAL=false
    healthcheck:
      test: ["CMD", "curl", "-fsS", "-H", "Authorization: youshallnotpass", "http://localhost:2333/version"]
      interval: 5s
      timeout: 5s
      retries: 5

  # The Discord Bot (Sermon)
  sermon:
    image: primemusic-bot
    container_name: sermon_bot
    restart: on-failure
    environment:
      TOKEN: ${SERMON_DISCORD_BOT_TOKEN}
      LANGUAGE: "en"
      OWNER_IDS: '["636950962245730324", "1441688644267282503", "1316933612645650505", "1484227086217646140"]'
      MONGODB_URI: "mongodb://admin:password@mongodb:27017/PrimeMusicSSRR?authSource=admin"
      SPOTIFY_CLIENT_ID: ""
      SPOTIFY_CLIENT_SECRET: ""
      SETUP_FILE_PATH: "./commands/setup.json"
      COMMANDS_DIR: "./commands"
      EMBED_COLOR: "#1d96e1"
      CUSTOM_EMOJI: "false"
      EMOJI_THEME: "redwhite"
      HELP_BANNER_URL: "https://remnantofgod.org/assets/img/wtpr-main-new.png"
      ACTIVITY_NAME: "WTPR"
      ACTIVITY_TYPE: "LISTENING"
      SUPPORT_SERVER: ""
      EMBED_TIMEOUT: "5"
      SHOW_PROGRESS_BAR: "true"
      SHOW_VISUALIZER: "false"
      GENERATE_SONG_CARD: "false"
      METADATA_TAG: "true"
      LOW_MEMORY_MODE: "true"
      ERROR_LOG: ""
      NODES: '[{"name":"LocalNode","password":"youshallnotpass","host":"tailscale_vpn","port":2333,"secure":false}]'
    depends_on:
      mongodb:
        condition: service_healthy
      lavalink:
        condition: service_healthy
    networks:
      - isolated_network

  # The Discord Bot (Music)
  musicbot:
    image: primemusic-bot
    container_name: music_bot
    restart: on-failure
    environment:
      TOKEN: ${MUSIC_DISCORD_BOT_TOKEN}
      LANGUAGE: "en"
      OWNER_IDS: '["636950962245730324", "1441688644267282503", "1316933612645650505", "1484227086217646140"]'
      MONGODB_URI: "mongodb://admin:password@mongodb:27017/PrimeMusicSSRR?authSource=admin"
      SPOTIFY_CLIENT_ID: ""
      SPOTIFY_CLIENT_SECRET: ""
      SETUP_FILE_PATH: "./commands/setup.json"
      COMMANDS_DIR: "./commands"
      EMBED_COLOR: "#1d96e1"
      CUSTOM_EMOJI: "false"
      EMOJI_THEME: "redwhite"
      HELP_BANNER_URL: ""
      ACTIVITY_NAME: "Music"
      ACTIVITY_TYPE: "LISTENING"
      SUPPORT_SERVER: ""
      EMBED_TIMEOUT: "5"
      SHOW_PROGRESS_BAR: "true"
      SHOW_VISUALIZER: "false"
      GENERATE_SONG_CARD: "false"
      METADATA_TAG: "true"
      LOW_MEMORY_MODE: "true"
      ERROR_LOG: ""
      NODES: '[{"name":"LocalNode","password":"youshallnotpass","host":"tailscale_vpn","port":2333,"secure":false}]'
    depends_on:
      mongodb:
        condition: service_healthy
      lavalink:
        condition: service_healthy
    networks:
      - isolated_network
  
  audiobiblebot:
    image: primemusic-bot
    container_name: audiobible_bot
    restart: on-failure
    environment:
      TOKEN: ${AUDIOBIBLE_DISCORD_BOT_TOKEN}
      LANGUAGE: "en"
      OWNER_IDS: '["636950962245730324", "1441688644267282503", "1316933612645650505", "1484227086217646140"]'
      MONGODB_URI: "mongodb://admin:password@mongodb:27017/PrimeMusicSSRR?authSource=admin"
      SPOTIFY_CLIENT_ID: ""
      SPOTIFY_CLIENT_SECRET: ""
      SETUP_FILE_PATH: "./commands/setup.json"
      COMMANDS_DIR: "./commands"
      EMBED_COLOR: "#1d96e1"
      CUSTOM_EMOJI: "false"
      EMOJI_THEME: "redwhite"
      HELP_BANNER_URL: ""
      ACTIVITY_NAME: "Bible"
      ACTIVITY_TYPE: "LISTENING"
      SUPPORT_SERVER: ""
      EMBED_TIMEOUT: "5"
      SHOW_PROGRESS_BAR: "true"
      SHOW_VISUALIZER: "false"
      GENERATE_SONG_CARD: "false"
      METADATA_TAG: "true"
      LOW_MEMORY_MODE: "true"
      ERROR_LOG: ""
      NODES: '[{"name":"LocalNode","password":"youshallnotpass","host":"tailscale_vpn","port":2333,"secure":false}]'
    depends_on:
      mongodb:
        condition: service_healthy
      lavalink:
        condition: service_healthy
    networks:
      - isolated_network

  healthylifebot:
    image: primemusic-bot
    container_name: healthylife_bot
    restart: on-failure
    environment:
      TOKEN: ${HEALTH_DISCORD_BOT_TOKEN}
      LANGUAGE: "en"
      OWNER_IDS: '["636950962245730324", "1441688644267282503", "1316933612645650505", "1484227086217646140"]'
      MONGODB_URI: "mongodb://admin:password@mongodb:27017/PrimeMusicSSRR?authSource=admin"
      SPOTIFY_CLIENT_ID: ""
      SPOTIFY_CLIENT_SECRET: ""
      SETUP_FILE_PATH: "./commands/setup.json"
      COMMANDS_DIR: "./commands"
      EMBED_COLOR: "#1d96e1"
      CUSTOM_EMOJI: "false"
      EMOJI_THEME: "redwhite"
      HELP_BANNER_URL: ""
      ACTIVITY_NAME: "Health"
      ACTIVITY_TYPE: "WATCHING"
      SUPPORT_SERVER: ""
      EMBED_TIMEOUT: "5"
      SHOW_PROGRESS_BAR: "true"
      SHOW_VISUALIZER: "false"
      GENERATE_SONG_CARD: "false"
      METADATA_TAG: "true"
      LOW_MEMORY_MODE: "true"
      ERROR_LOG: ""
      NODES: '[{"name":"LocalNode","password":"youshallnotpass","host":"tailscale_vpn","port":2333,"secure":false}]'
    depends_on:
      mongodb:
        condition: service_healthy
      lavalink:
        condition: service_healthy
    networks:
      - isolated_network

  audiobot:
    image: primemusic-bot
    container_name: audio_bot
    restart: on-failure
    environment:
      TOKEN: ${AUDIO_DISCORD_BOT_TOKEN}
      LANGUAGE: "en"
      OWNER_IDS: '["636950962245730324", "1441688644267282503", "1316933612645650505", "1484227086217646140"]'
      MONGODB_URI: "mongodb://admin:password@mongodb:27017/PrimeMusicSSRR?authSource=admin"
      SPOTIFY_CLIENT_ID: ""
      SPOTIFY_CLIENT_SECRET: ""
      SETUP_FILE_PATH: "./commands/setup.json"
      COMMANDS_DIR: "./commands"
      EMBED_COLOR: "#1d96e1"
      CUSTOM_EMOJI: "false"
      EMOJI_THEME: "redwhite"
      HELP_BANNER_URL: ""
      ACTIVITY_NAME: "Audio"
      ACTIVITY_TYPE: "LISTENING"
      SUPPORT_SERVER: ""
      EMBED_TIMEOUT: "5"
      SHOW_PROGRESS_BAR: "true"
      SHOW_VISUALIZER: "false"
      GENERATE_SONG_CARD: "false"
      METADATA_TAG: "true"
      LOW_MEMORY_MODE: "true"
      ERROR_LOG: ""
      NODES: '[{"name":"LocalNode","password":"youshallnotpass","host":"tailscale_vpn","port":2333,"secure":false}]'
    depends_on:
      mongodb:
        condition: service_healthy
      lavalink:
        condition: service_healthy
    networks:
      - isolated_network

volumes:
  mongodb_data:
    driver: local
  filebrowser_data:
    driver: local
  tailscale_data:
    driver: local

networks:
  isolated_network:
    driver: bridge

# Audio Bible bot: https://discord.com/oauth2/authorize?client_id=1524764283924385832&permissions=845118570981696&integration_type=0&scope=bot
# Blessed Music: https://discord.com/oauth2/authorize?client_id=1392081306942312528&permissions=281614566557952&integration_type=0&scope=bot
# Sermons: https://discord.com/oauth2/authorize?client_id=1399306314491891753&permissions=281614566557952&integration_type=0&scope=bot 
# Promises bot: https://discord.com/oauth2/authorize?client_id=1363443384957800468&permissions=139586791488&integration_type=0&scope=bot
# Health bot: https://discord.com/oauth2/authorize?client_id=1527650799583498360&permissions=282168650975488&integration_type=0&scope=bot
# Audio bot: https://discord.com/oauth2/authorize?client_id=1527418432583237873&permissions=5348718231779648&integration_type=0&scope=bot
